# Generated by Django 5.2.6 on 2025-11-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_merchantprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
