# Generated by Django 5.2.6 on 2025-11-04 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=100, unique=True)),
                ('customer_number', models.CharField(max_length=200)),
                ('customer_message', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField()),
                ('shipping_status', models.CharField(choices=[('0', 'Not Shipped'), ('1', 'Processing'), ('2', 'Shipped'), ('3', 'In Transit'), ('4', 'Out for Delivery'), ('5', 'Delivered'), ('6', 'Returned')], default='0', max_length=1)),
                ('payment_status', models.CharField(choices=[('0', 'Pending'), ('1', 'Completed'), ('2', 'Failed'), ('3', 'Refunded')], default='0', max_length=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined')], default='accepted', max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('declined_at', models.DateTimeField(blank=True, help_text='Only if this product is declined', null=True)),
                ('order_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order')),
                ('product_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
